project:
  type: website
  output-dir: docs

website:
  title: "Revisitando las encuestas"
  repo-url: https://github.com/PoliCICS/revisiting-surveys-workshop
  repo-actions: [edit, source]
  navbar:
    left:
      - text: Home
        href: 0-index.qmd
      - text: Módulos
        menu:
          - text: Introducción
            href: 1-introduction.qmd
          - text: Calculando la Fuerza Homofílica
            href: 2-homophily-strength.qmd
          - text: Imputando Contexto Social a las encuestas
            href: 3-network-from-surveys.qmd
          - text: Ising & Psicometría
            href: 3-ising.qmd
    right:
      - text: Recursos
        menu:
          - text: Get Started
            href: getstarted.qmd
          - text: Limpieza GSS 2004
            href: gss-cleaning.qmd
          - text: Limpieza ANES 2016
            href: anes-cleaning.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    code-fold: show
    code-tools: true
    embed-resources: true
    lang: es

execute:
  freeze: auto
